import fs from 'node:fs/promises';
import path from 'node:path';
import { getClickHouseClient } from '../utils/clickhouse-client.js';

export interface ClickHouseGeneratorOptions {
  outputPath: string;
  includeTables?: string[];
  excludeTables?: string[];
}

interface ClickHouseTable {
  name: string;
}

interface ClickHouseColumn {
  name: string;
  type: string;
}

const DEFAULT_WARNING =
  'Warning: No tables match the filter criteria. Check your include/exclude options.';

const capitalizeFirstLetter = (value: string) => value.charAt(0).toUpperCase() + value.slice(1);

function splitTopLevelArgs(value: string): string[] {
  const parts: string[] = [];
  let current = '';
  let depth = 0;

  for (const char of value) {
    if (char === '(') {
      depth += 1;
      current += char;
      continue;
    }

    if (char === ')') {
      depth -= 1;
      current += char;
      continue;
    }

    if (char === ',' && depth === 0) {
      parts.push(current.trim());
      current = '';
      continue;
    }

    current += char;
  }

  if (current.trim()) {
    parts.push(current.trim());
  }

  return parts;
}

function unwrapType(type: string, wrapperName: string): string | null {
  const prefix = `${wrapperName}(`;
  return type.startsWith(prefix) && type.endsWith(')') ? type.slice(prefix.length, -1) : null;
}

function getPrimitiveTsType(type: string): string | null {
  const lowerType = type.toLowerCase();

  switch (lowerType) {
    case 'string':
    case 'uuid':
      return 'string';
    case 'int8':
    case 'int16':
    case 'int32':
    case 'uint8':
    case 'uint16':
    case 'uint32':
      return 'number';
    case 'int64':
    case 'uint64':
    case 'uint128':
    case 'uint256':
    case 'int128':
    case 'int256':
      return 'string';
    case 'float32':
    case 'float64':
    case 'decimal':
      return 'number';
    case 'datetime':
    case 'datetime64':
    case 'date':
    case 'date32':
      return 'string';
    case 'bool':
    case 'boolean':
      return 'boolean';
    default:
      if (type.startsWith('FixedString(')) return 'string';
      if (type.startsWith('Decimal(')) return 'number';
      if (type.startsWith('DateTime64(')) return 'string';
      if (type.startsWith('DateTime(')) return 'string';
      if (type.startsWith('Enum8(')) return 'string';
      if (type.startsWith('Enum16(')) return 'string';
      return null;
  }
}

const clickhouseToTsType = (type: string): string => {
  const wrappedArrayType = unwrapType(type, 'Array');
  if (wrappedArrayType) {
    return `Array<${clickhouseToTsType(wrappedArrayType)}>`;
  }

  const wrappedNullableType = unwrapType(type, 'Nullable');
  if (wrappedNullableType) {
    return `${clickhouseToTsType(wrappedNullableType)} | null`;
  }

  const wrappedLowCardinalityType = unwrapType(type, 'LowCardinality');
  if (wrappedLowCardinalityType) {
    return clickhouseToTsType(wrappedLowCardinalityType);
  }

  const wrappedTupleType = unwrapType(type, 'Tuple');
  if (wrappedTupleType) {
    const tupleParts = splitTopLevelArgs(wrappedTupleType);
    return `[${tupleParts.map(clickhouseToTsType).join(', ')}]`;
  }

  const wrappedMapType = unwrapType(type, 'Map');
  if (wrappedMapType) {
    const mapParts = splitTopLevelArgs(wrappedMapType);
    if (mapParts.length === 2) {
      const [, valueType] = mapParts;
      // JSON object keys are strings even when ClickHouse map keys are numeric.
      return `Record<string, ${clickhouseToTsType(valueType)}>`;
    }
    return 'Record<string, unknown>';
  }

  const primitiveType = getPrimitiveTsType(type);
  if (primitiveType) return primitiveType;

  // Unsupported or more complex ClickHouse types currently preserve the historical fallback.
  return 'string';
};

export { clickhouseToTsType };

async function fetchTables(includeTables?: string[], excludeTables?: string[]) {
  const client = getClickHouseClient();
  const tablesQuery = await client.query({
    query: 'SHOW TABLES',
    format: 'JSONEachRow',
  });

  let tables = (await tablesQuery.json()) as ClickHouseTable[];

  if (includeTables?.length) {
    tables = tables.filter(table => includeTables.includes(table.name));
  }

  if (excludeTables?.length) {
    tables = tables.filter(table => !excludeTables.includes(table.name));
  }

  return tables;
}

async function fetchColumns(table: string) {
  const client = getClickHouseClient();
  const columnsQuery = await client.query({
    query: `DESCRIBE TABLE ${table}`,
    format: 'JSONEachRow',
  });

  return (await columnsQuery.json()) as ClickHouseColumn[];
}

export async function generateClickHouseTypes(options: ClickHouseGeneratorOptions) {
  const { outputPath, includeTables, excludeTables } = options;

  const tables = await fetchTables(includeTables, excludeTables);

  if (tables.length === 0) {
    console.warn(DEFAULT_WARNING);
  }

  let typeDefinitions = `// Generated by hypequery\n` +
    `// This file defines TypeScript types based on your ClickHouse database schema\n\n` +
    `export interface IntrospectedSchema {`;

  for (const table of tables) {
    const columns = await fetchColumns(table.name);
    typeDefinitions += `\n  ${table.name}: {`;

    for (const column of columns) {
      const clickHouseType = column.type.replace(/'/g, "\\'");
      typeDefinitions += `\n    '${column.name}': '${clickHouseType}';`;
    }

    typeDefinitions += '\n  };';
  }

  typeDefinitions += '\n}\n';
  typeDefinitions += `\n// Type-safe record types for each table\n`;

  for (const table of tables) {
    const columns = await fetchColumns(table.name);
    typeDefinitions += `export interface ${capitalizeFirstLetter(table.name)}Record {`;

    for (const column of columns) {
      const tsType = clickhouseToTsType(column.type).replace(/'/g, '');
      typeDefinitions += `\n  '${column.name}': ${tsType};`;
    }

    typeDefinitions += '\n}\n\n';
  }
  const outputDir = path.dirname(path.resolve(outputPath));
  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(path.resolve(outputPath), typeDefinitions);
}
