// Generated by scripts/generate-version.mjs. Do not edit.
//
// Resolved at build time rather than read from package.json at import time, so
// importing this package touches no filesystem and survives bundling.
export const MCP_PACKAGE_VERSION = '0.5.5';
