import type { Metadata } from 'next';
import { ClickhousePillarPage } from '@/components/clickhouse-pillar-page';
import { absoluteUrl } from '@/lib/site';

export const metadata: Metadata = {
  title: 'ClickHouse Audit Log — TypeScript Query Layer for Event Logs | hypequery',
  description:
    'Build audit-log APIs on ClickHouse with typed filters, cursor pagination, and reviewable tenant scoping patterns for append-only event tables.',
  alternates: {
    canonical: absoluteUrl('/clickhouse-audit-log'),
  },
  openGraph: {
    type: 'website',
    url: absoluteUrl('/clickhouse-audit-log'),
    title: 'ClickHouse Audit Log — TypeScript Query Layer for Event Logs | hypequery',
    description:
      'Build audit-log APIs on ClickHouse with typed filters, cursor pagination, and reviewable tenant scoping patterns for append-only event tables.',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'ClickHouse Audit Log — TypeScript Query Layer for Event Logs | hypequery',
    description:
      'Build audit-log APIs on ClickHouse with typed filters, cursor pagination, and reviewable tenant scoping patterns for append-only event tables.',
  },
};

const schemaAndQueryCode = `// Generated by: npx @hypequery/cli generate --output ./schema.ts
// Reflects the actual audit_log table structure in ClickHouse.
//
// ClickHouse type → TypeScript type
//   DateTime      → string
//   UInt64        → string
//   Nullable(T)   → T | null
//
// type AuditLogRow = {
//   id: string;            // UInt64
//   tenant_id: string;
//   actor_id: string;
//   actor_type: string;    // 'user' | 'api_key' | 'system'
//   action: string;        // 'create' | 'update' | 'delete' | 'read' | ...
//   resource_type: string;
//   resource_id: string;   // UInt64
//   ip_address: string | null;
//   metadata: string | null; // JSON string
//   created_at: string;    // DateTime
// }

import { createQueryBuilder } from '@hypequery/clickhouse';
import type { Schema } from './schema';

const db = createQueryBuilder<Schema>({ /* connection config */ });

// Typed query — column names and filter types verified at compile time
export async function queryAuditLog(opts: {
  tenantId: string;
  actorId?: string;
  action?: string;
  resourceType?: string;
  startDate: string;
  endDate: string;
  limit: number;
  offset: number;
}) {
  let q = db
    .table('audit_log')
    .select(
      'id', 'actor_id', 'actor_type', 'action',
      'resource_type', 'resource_id', 'ip_address',
      'metadata', 'created_at',
    )
    .where('tenant_id', 'eq', opts.tenantId)
    .where('created_at', 'gte', opts.startDate)
    .where('created_at', 'lte', opts.endDate);

  if (opts.actorId)     q = q.where('actor_id', 'eq', opts.actorId);
  if (opts.action)      q = q.where('action', 'eq', opts.action);
  if (opts.resourceType) q = q.where('resource_type', 'eq', opts.resourceType);

  return q
    .orderBy('created_at', 'DESC')
    .limit(opts.limit)
    .offset(opts.offset)
    .execute();
}`;

const auditApiCode = `// analytics/audit-log-api.ts
import { initServe } from '@hypequery/serve';
import { db } from '@/lib/clickhouse';
import { z } from 'zod';

const { query, serve } = initServe({
  // Tenant isolation applied once — every query below is automatically scoped
  context: (req) => ({
    db,
    tenantId: req.headers['x-tenant-id'] as string,
  }),
});

const auditEvents = query({
  input: z.object({
    actorId:      z.string().optional(),
    action:       z.string().optional(),
    resourceType: z.string().optional(),
    startDate:    z.string(),
    endDate:      z.string(),
    limit:        z.number().int().min(1).max(200).default(50),
    cursor:       z.string().optional(), // cursor = base64(created_at + ':' + id)
  }),
  query: ({ ctx, input }) => {
    let q = ctx.db
      .table('audit_log')
      .select(
        'id', 'actor_id', 'actor_type', 'action',
        'resource_type', 'resource_id', 'ip_address',
        'created_at',
      )
      .where('tenant_id', 'eq', ctx.tenantId)    // enforced in the shared query path
      .where('created_at', 'gte', input.startDate)
      .where('created_at', 'lte', input.endDate);

    if (input.actorId)      q = q.where('actor_id', 'eq', input.actorId);
    if (input.action)       q = q.where('action', 'eq', input.action);
    if (input.resourceType) q = q.where('resource_type', 'eq', input.resourceType);

    if (input.cursor) {
      const [ts, id] = decodeCursor(input.cursor);
      // Keyset pagination — more stable than OFFSET on append-only tables
      q = q.where('created_at', 'lte', ts).where('id', 'lt', id);
    }

    return q
      .orderBy('created_at', 'DESC')
      .orderBy('id', 'DESC')
      .limit(input.limit + 1)   // fetch one extra to detect next page
      .execute();
  },
});

const auditSummary = query({
  input: z.object({ startDate: z.string(), endDate: z.string() }),
  query: ({ ctx, input }) =>
    ctx.db
      .table('audit_log')
      .select('action', 'actor_type', 'count() as event_count')
      .where('tenant_id', 'eq', ctx.tenantId)
      .where('created_at', 'gte', input.startDate)
      .where('created_at', 'lte', input.endDate)
      .groupBy('action', 'actor_type')
      .orderBy('event_count', 'DESC')
      .execute(),
});

export const api = serve({ queries: { auditEvents, auditSummary } });

function decodeCursor(cursor: string): [string, string] {
  const [ts, id] = Buffer.from(cursor, 'base64').toString().split(':');
  return [ts, id];
}`;

export default function ClickHouseAuditLogPage() {
  return (
    <ClickhousePillarPage
      eyebrow="ClickHouse Audit Log"
      title="Query ClickHouse audit logs with TypeScript and full type safety"
      description="ClickHouse is well-suited for append-only audit log storage at scale. The challenge is building the TypeScript query layer around it — typed filters, strict tenant isolation, and paginated HTTP endpoints — without writing it from scratch for every project."
      primaryCta={{ href: '/docs/quick-start', label: 'Open quick start' }}
      secondaryCta={{ href: '/clickhouse-multi-tenant-analytics', label: 'See tenant isolation patterns' }}
      stats={[
        { label: 'Table pattern', value: 'Append-only audit_log' },
        { label: 'Isolation', value: 'Shared tenant-scoped query path' },
        { label: 'Pagination', value: 'Keyset (cursor) pagination' },
      ]}
      problems={[
        {
          title: 'Audit log tables have many columns that drift as new event types are added',
          copy:
            'Audit log tables tend to grow: actor fields, resource fields, action types, metadata columns. Hand-written TypeScript interfaces for them become stale quickly. Schema-generated types that reflect the live ClickHouse table are the only reliable approach.',
        },
        {
          title: 'Audit log queries need strict tenant isolation — a leak exposes one customer\'s actions to another',
          copy:
            'Tenant isolation in audit logs is a compliance requirement, not just a product feature. A WHERE tenant_id = ? clause in every query is easy to forget. A context-level isolation pattern that applies the filter structurally is much harder to bypass accidentally.',
        },
        {
          title: 'Exposing audit logs via API requires filtering, pagination, and sometimes search',
          copy:
            'A production audit log API needs actor filtering, action filtering, date ranges, and cursor-based pagination on an append-only table. Writing that from scratch on raw ClickHouse queries for every project is repetitive and error-prone.',
        },
      ]}
      solutionSection={{
        eyebrow: 'Schema types and typed queries',
        title: 'Generate audit log types from ClickHouse, compose typed filters in TypeScript',
        description:
          'ClickHouse DateTime columns return as strings, UInt64 columns return as strings, and Nullable columns return T | null. Schema generation captures all of these mappings so the TypeScript layer reflects what ClickHouse actually returns.',
        bullets: [
          'Run npx @hypequery/cli generate to emit TypeScript types from the audit_log table',
          'DateTime → string, UInt64 → string, Nullable(T) → T | null',
          'Compose filters (actor, action, resource, date range) as typed .where() calls',
          'Add optional filters conditionally — no string interpolation, no SQL injection risk',
          'Use .orderBy("created_at", "DESC") with keyset pagination for stable results on append-only tables',
        ],
        codePanel: {
          eyebrow: 'Schema types and query',
          title: 'Schema-generated audit log types and a composable typed query',
          description:
            'The type comment at the top reflects what the CLI actually generates. Column renames or type changes in ClickHouse surface as TypeScript compile errors before reaching production.',
          code: schemaAndQueryCode,
        },
      }}
      implementationSection={{
        eyebrow: 'Typed audit log API',
        title: 'Tenant-isolated audit log endpoint with keyset pagination',
        description:
          'The serve layer applies tenant scoping once in context and keeps it in the shared query path. Adding a new audit query no longer means re-implementing auth and pagination concerns from scratch.',
        paragraphs: [
          'Keyset (cursor) pagination is more appropriate than OFFSET for audit logs. ClickHouse append-only tables are written to constantly, so OFFSET results shift between pages. Cursor pagination based on created_at and id gives stable pages.',
          'The summary endpoint shows how the same tenant-isolated context can power both paginated event lists and aggregated activity summaries from the same API definition.',
        ],
        codePanel: {
          eyebrow: 'Audit log API',
          title: 'Tenant-isolated, cursor-paginated audit log API',
          description:
            'One context definition provides tenant isolation for all queries. The cursor encodes the last-seen timestamp and ID, which is stable on append-only ClickHouse tables.',
          code: auditApiCode,
        },
      }}
      searchIntentCards={[
        {
          title: 'ClickHouse audit log TypeScript',
          copy:
            'Building a TypeScript audit log on ClickHouse requires schema-generated types, composable typed filters, and a tenant scoping pattern that stays visible in code review instead of hiding in ad hoc route logic.',
        },
        {
          title: 'ClickHouse event log queries',
          copy:
            'Querying event logs in ClickHouse is efficient when combined with correct ordering keys. The application layer should add typed filters and pagination on top of that structure.',
        },
        {
          title: 'ClickHouse audit trail API',
          copy:
            'An audit trail API on ClickHouse needs actor filtering, action filtering, date range filtering, and stable pagination. hypequery gives all of those through typed .where() composition and a serve layer.',
        },
        {
          title: 'ClickHouse tenant audit logs',
          copy:
            'Tenant isolation for audit logs is best handled at context level — not scattered across individual queries. A structural approach ensures the isolation is never missing from a new endpoint.',
        },
      ]}
      readingLinks={[
        {
          href: '/clickhouse-multi-tenant-analytics',
          title: 'ClickHouse Multi-Tenant Analytics',
          description: 'Deeper treatment of tenant isolation patterns and safe multi-tenant query design.',
        },
        {
          href: '/clickhouse-rest-api',
          title: 'ClickHouse REST API',
          description: 'Expose typed ClickHouse queries as HTTP endpoints with input validation.',
        },
        {
          href: '/clickhouse-saas-analytics',
          title: 'ClickHouse SaaS Analytics',
          description: 'Customer-facing analytics and audit logs in a SaaS product.',
        },
        {
          href: '/clickhouse-typescript',
          title: 'ClickHouse TypeScript',
          description: 'ClickHouse type mappings and schema generation details.',
        },
      ]}
      relatedPillars={[
        { href: '/clickhouse-multi-tenant-analytics', label: 'ClickHouse Multi-Tenant Analytics' },
        { href: '/clickhouse-rest-api', label: 'ClickHouse REST API' },
        { href: '/clickhouse-saas-analytics', label: 'ClickHouse SaaS Analytics' },
        { href: '/clickhouse-typescript', label: 'ClickHouse TypeScript' },
      ]}
      nextStep={{
        eyebrow: 'Next step',
        title: 'Generate your audit log schema and write the first tenant-isolated query',
        description:
          'Schema generation captures the real column types from your audit_log table. From there, a tenant-isolated API endpoint with cursor pagination follows the same pattern shown above.',
        primaryCta: { href: '/docs/quick-start', label: 'Open quick start' },
        secondaryCta: { href: '/clickhouse-multi-tenant-analytics', label: 'See tenant isolation patterns' },
      }}
    />
  );
}
