import { COMMON_PROPERTIES, EVENT_CATALOG, EVENT_SCHEMA_VERSION } from './catalog.js';
import type { Field, Fields } from './schema.js';
import { VALUE_FORMATS } from './value-formats.js';
import { COMMAND_FLAGS, GLOBAL_FLAGS } from './domains.js';

function domain(field: Field): string {
  switch (field.kind) {
    case 'boolean': return '`true`, `false`';
    case 'enum': return field.values.map(value => `\`${value}\``).join(', ');
    case 'enum_list': return `Unique list of: ${field.values.map(value => `\`${value}\``).join(', ')}`;
    case 'record': return 'Object with only the documented keys below';
    case 'format': return VALUE_FORMATS[field.format].description;
  }
}

function rows(fields: Fields, prefix = ''): string[] {
  return Object.entries(fields).flatMap(([name, field]) => {
    const key = `${prefix}${name}`;
    return [
      `| \`${key}\` | ${field.optional ? 'Optional' : 'Required'} | ${domain(field)} | ${field.description} |`,
      ...(field.kind === 'record' ? rows(field.fields, `${key}.`) : []),
    ];
  });
}

function table(fields: Fields): string {
  return ['| Property | Presence | Allowed values | Question answered |', '| --- | --- | --- | --- |', ...rows(fields)].join('\n');
}

/** Generated section only; the public page retains its human-written policy and controls. */
export function renderTelemetryCatalog(): string {
  const parts = [
    '{/* Generated by pnpm --filter @hypequery/cli telemetry:docs. Do not edit this section by hand. */}',
    '## Event reference',
    `Schema version: **${EVENT_SCHEMA_VERSION}**. Default collection is inactive. Debug or explicitly configured ingest mode emits command/crash lifecycle events, init and generation metrics, and dev/MCP session events. Cloud command and project-feature instrumentation follows separately.`,
    'Unknown events, properties, record keys, flag names, enum values, and malformed identities or versions are rejected. No argument values, paths, names, SQL, messages, stacks, hosts, tenants, or credentials are permitted.',
    'Counts use inclusive integer ranges: 0, 1, 2–5, 6–20, 21–100, and 101 or more. Duration and nonzero size buckets include their lower bound and exclude their upper bound. Raw counts, durations, ports and byte sizes are never sent.',
    '### Common properties',
    'Every event includes these fields. Unknown environment details use the documented unknown value; unavailable optional fields are omitted.',
    table(COMMON_PROPERTIES),
  ];
  for (const [name, definition] of Object.entries(EVENT_CATALOG)) {
    parts.push(`### \`${name}\``, definition.purpose, table(definition.properties));
    if ('variants' in definition) {
      for (const [command, fields] of Object.entries(definition.variants)) {
        parts.push(`#### \`${name}\`: \`${command}\``);
        if (name === 'cli_command_completed') {
          const flags = [...COMMAND_FLAGS[command as keyof typeof COMMAND_FLAGS], ...GLOBAL_FLAGS];
          parts.push(`Allowed \`flags_used\`: ${flags.map(flag => `\`${flag}\``).join(', ')}. The two type-generation aliases remain distinct command values.`);
        }
        parts.push(Object.keys(fields).length ? table(fields) : 'No additional properties.');
      }
    }
  }
  parts.push('MCP client identity/version is excluded from v1 pending the privacy decision. Auth strategies are recorded only as none/configured/unknown, since user-supplied functions have no safe built-in type identifier.',
    'Cache scopes are classified only as unscoped/tenant/explicit/unknown from configuration presence. Explicit scopes are user content and are never read into a payload.',
    'Project IDs follow HQ-233: the CLI uses the shared global salt, then the ingest proxy re-keys the digest with a server-side HMAC secret before storage. A hash is a pseudonymous project signal, not proof of anonymity. Cloud accounts are never linked to install IDs.');
  return `${parts.join('\n\n')}\n`;
}
