packages:
  - 'packages/cli'
  - 'packages/clickhouse'
  - 'packages/react'
  - 'packages/schema'
  - 'packages/datasets'
  - 'packages/gateway'
  - 'packages/serve'
  - 'packages/studio'
  - 'packages/mcp-server'
  - 'packages/protocol'
  - 'packages/tsconfig'
  - 'examples/*'
