packages:
  - 'packages/cli'
  - 'packages/clickhouse'
  - 'packages/create-app'
  - 'packages/react'
  - 'packages/serve'
  - 'packages/serve-ui'
  - 'packages/tsconfig'
  - 'examples/*'
onlyBuiltDependencies:
  - better-sqlite3
