import { ClickHouseConnection } from '../core/connection.js';
import { ColumnType } from '../types/base.js';
import fs from 'fs/promises';
import path from 'path';
import dotenv from 'dotenv';
import { fileURLToPath } from 'url';

// Load environment variables from the example app
dotenv.config({
  path: path.resolve(process.cwd(), '../../examples/basic-dashboard/.env')
});

interface ColumnInfo {
  name: string;
  type: string;
}

const clickhouseToTsType = (type: string): ColumnType => {
  if (type.startsWith('Array(')) {
    const innerType = type.slice(6, -1);
    return `Array(${clickhouseToTsType(innerType)})` as ColumnType;
  }

  switch (type.toLowerCase()) {
    case 'string':
    case 'fixedstring':
      return 'String';
    case 'int8':
    case 'int16':
    case 'int32':
      return 'Int32';
    case 'int64':
      return 'Int64';
    case 'float32':
    case 'float64':
      return 'Float64';
    case 'datetime':
      return 'DateTime';
    case 'date':
      return 'Date';
    default:
      return 'String';
  }
};

async function generateTypes(outputPath: string) {
  const client = ClickHouseConnection.getClient();

  // Get all tables
  const tablesQuery = await client.query({
    query: 'SHOW TABLES',
    format: 'JSONEachRow'
  });
  const tables = await tablesQuery.json<{ name: string }[]>();

  let typeDefinitions = `// Generated by @hypequery/core/cli
import { ColumnType } from '@hypequery/core';

export interface IntrospectedSchema {`;

  // Get columns for each table
  for (const table of tables) {
    const columnsQuery = await client.query({
      query: `DESCRIBE ${table.name}`,
      format: 'JSONEachRow'
    });
    const columns = await columnsQuery.json<ColumnInfo[]>();

    typeDefinitions += `\n  ${table.name}: {`;
    for (const column of columns) {
      typeDefinitions += `\n    ${column.name}: '${clickhouseToTsType(column.type)}';`;
    }
    typeDefinitions += '\n  };';
  }

  typeDefinitions += '\n}\n';

  await fs.writeFile(path.resolve(outputPath), typeDefinitions);
}

// CLI entry point
async function main() {
  const outputPath = process.argv[2] || './generated-schema.ts';

  try {
    // Initialize connection from env vars
    ClickHouseConnection.initialize({
      host: process.env.VITE_CLICKHOUSE_HOST || 'http://localhost:8123',
      username: process.env.VITE_CLICKHOUSE_USER || 'default',
      password: process.env.VITE_CLICKHOUSE_PASSWORD,
      database: process.env.VITE_CLICKHOUSE_DATABASE,
    });

    await generateTypes(outputPath);
    console.log(`✨ Types generated successfully at ${outputPath}`);
  } catch (error) {
    console.error('Error generating types:', error);
    process.exit(1);
  }
}

// Replace the import.meta check with a simpler approach
const isMainModule = process.argv[1] === fileURLToPath(import.meta.url);
if (isMainModule) {
  main();
} 