import { defineSchema } from '../schema/define.js';
import type {
  ClickHouseColumnDefaultValue,
  ClickHouseColumnType,
  ClickHouseSchemaAst,
  ClickHouseTableDefinition,
} from '../schema/types.js';

export interface IntrospectedTableRow {
  name: string;
  engine: string;
  partitionKey: string;
  sortingKey: string;
  primaryKey: string;
  samplingKey: string;
}

export interface IntrospectedColumnRow {
  table: string;
  name: string;
  type: string;
  defaultKind?: string | null;
  defaultExpression?: string | null;
  position: number;
}

export function buildPulledSchemaAst(
  tables: IntrospectedTableRow[],
  columns: IntrospectedColumnRow[],
): ClickHouseSchemaAst {
  const columnsByTable = new Map<string, IntrospectedColumnRow[]>();

  for (const column of columns) {
    const existing = columnsByTable.get(column.table) ?? [];
    existing.push(column);
    columnsByTable.set(column.table, existing);
  }

  const schemaTables: ClickHouseTableDefinition[] = tables.map((table) => ({
    kind: 'table',
    name: table.name,
    columns: (columnsByTable.get(table.name) ?? [])
      .sort((left, right) => left.position - right.position)
      .map((column) => ({
        name: column.name,
        type: parseColumnType(column.type),
        ...(toColumnDefault(column) ? { default: toColumnDefault(column)! } : {}),
      })),
    engine: {
      type: table.engine,
      orderBy: table.sortingKey ? splitTopLevelArgs(table.sortingKey) : [],
      ...(table.partitionKey ? { partitionBy: table.partitionKey } : {}),
      ...(table.primaryKey ? { primaryKey: splitTopLevelArgs(table.primaryKey) } : {}),
      ...(table.samplingKey ? { sampleBy: table.samplingKey } : {}),
    },
  }));

  return defineSchema({
    tables: schemaTables,
  });
}

export function renderPulledSchemaSource(
  schema: ClickHouseSchemaAst,
  context: {
    database: string;
    materializedViewCount: number;
  },
): string {
  const lines = [
    `import { defineSchema } from '@hypequery/clickhouse';`,
    ``,
    `// Generated by \`hypequery pull\` from ClickHouse database "${context.database}".`,
    `// This baseline currently emits managed tables and column defaults.`,
    `// Table settings and materialized views still require manual follow-up.`,
  ];

  if (context.materializedViewCount > 0) {
    lines.push(`// Skipped ${context.materializedViewCount} materialized view${context.materializedViewCount === 1 ? '' : 's'} during baseline generation.`);
  }

  lines.push(
    ``,
    `export const schema = defineSchema(${renderValue({ tables: schema.tables })});`,
    ``,
    `export default schema;`,
    ``,
  );

  return lines.join('\n');
}

function parseColumnType(type: string): ClickHouseColumnType {
  const normalized = type.trim();

  if (normalized.startsWith('Nullable(') && normalized.endsWith(')')) {
    return {
      kind: 'nullable',
      inner: parseColumnType(normalized.slice('Nullable('.length, -1)),
    };
  }

  if (normalized.startsWith('LowCardinality(') && normalized.endsWith(')')) {
    return {
      kind: 'low_cardinality',
      inner: parseColumnType(normalized.slice('LowCardinality('.length, -1)),
    };
  }

  const match = normalized.match(/^([A-Za-z0-9_]+)(?:\((.*)\))?$/);
  if (!match) {
    return {
      kind: 'named',
      name: normalized,
    };
  }

  const [, name, args] = match;
  return {
    kind: 'named',
    name,
    ...(args !== undefined && args.trim().length > 0
      ? {
          arguments: splitTopLevelArgs(args).map((value) => {
            const trimmed = value.trim();
            return /^-?\d+(?:\.\d+)?$/.test(trimmed) ? Number(trimmed) : trimmed;
          }),
        }
      : {}),
  };
}

function toColumnDefault(column: IntrospectedColumnRow): ClickHouseColumnDefaultValue | undefined {
  if (!column.defaultExpression) {
    return undefined;
  }

  return {
    kind: 'sql',
    value: column.defaultExpression,
  };
}

function renderValue(value: unknown, indentLevel = 0): string {
  const indent = '  '.repeat(indentLevel);
  const nextIndent = '  '.repeat(indentLevel + 1);

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return '[]';
    }

    return `[\n${value.map(item => `${nextIndent}${renderValue(item, indentLevel + 1)}`).join(',\n')}\n${indent}]`;
  }

  if (value && typeof value === 'object') {
    const entries = Object.entries(value);
    if (entries.length === 0) {
      return '{}';
    }

    return `{\n${entries.map(([key, entryValue]) => `${nextIndent}${key}: ${renderValue(entryValue, indentLevel + 1)}`).join(',\n')}\n${indent}}`;
  }

  return JSON.stringify(value);
}

function splitTopLevelArgs(value: string): string[] {
  const parts: string[] = [];
  let current = '';
  let depth = 0;

  for (const char of value) {
    if (char === '(') {
      depth += 1;
      current += char;
      continue;
    }

    if (char === ')') {
      depth -= 1;
      current += char;
      continue;
    }

    if (char === ',' && depth === 0) {
      if (current.trim()) {
        parts.push(current.trim());
      }
      current = '';
      continue;
    }

    current += char;
  }

  if (current.trim()) {
    parts.push(current.trim());
  }

  return parts;
}
