#!/usr/bin/env tsx
/**
 * Embeds the serve-ui dist into a generated TypeScript module.
 * This runs as a pre-build step so the UI is always available at runtime
 * without requiring users to build serve-ui separately.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'fs';
import { execSync } from 'child_process';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const serveUIDir = join(__dirname, '../../serve-ui');
const serveUIDistDir = join(serveUIDir, 'dist');
const outputFile = join(__dirname, '../src/dev-ui/embedded-assets.ts');

function escapeString(str: string): string {
  return str
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$');
}

function buildServeUI(): boolean {
  if (!existsSync(join(serveUIDir, 'package.json'))) {
    return false;
  }
  try {
    console.log('[embed-ui] Building serve-ui...');
    execSync('npm run build', { cwd: serveUIDir, stdio: 'inherit' });
    return existsSync(join(serveUIDistDir, 'index.html'));
  } catch {
    console.warn('[embed-ui] Failed to build serve-ui');
    return false;
  }
}

function generateEmpty(): void {
  writeFileSync(outputFile, `// Auto-generated - no UI assets available
export const EMBEDDED_HTML: string | null = null;
export const EMBEDDED_JS: Record<string, string> = {};
export const EMBEDDED_CSS: Record<string, string> = {};
`);
}

function generate(): void {
  if (!existsSync(serveUIDistDir) || !existsSync(join(serveUIDistDir, 'index.html'))) {
    // Try to build serve-ui automatically
    if (!buildServeUI()) {
      console.warn('[embed-ui] serve-ui dist not available, generating empty assets');
      generateEmpty();
      return;
    }
  }

  // Read and rewrite HTML paths
  let html = readFileSync(join(serveUIDistDir, 'index.html'), 'utf-8');
  html = html.replace(/\/assets\//g, '/__dev/assets/');

  // Read assets
  const assetsDir = join(serveUIDistDir, 'assets');
  const jsFiles: Record<string, string> = {};
  const cssFiles: Record<string, string> = {};

  if (existsSync(assetsDir)) {
    for (const file of readdirSync(assetsDir)) {
      const filePath = join(assetsDir, file);
      if (file.endsWith('.js') && !file.endsWith('.js.map')) {
        jsFiles[file] = readFileSync(filePath, 'utf-8');
      } else if (file.endsWith('.css')) {
        cssFiles[file] = readFileSync(filePath, 'utf-8');
      }
    }
  }

  // Generate TypeScript module
  const lines: string[] = [
    '// Auto-generated by scripts/embed-ui.ts - DO NOT EDIT',
    '// Contains the embedded serve-ui build artifacts',
    '',
    `export const EMBEDDED_HTML: string | null = \`${escapeString(html)}\`;`,
    '',
    'export const EMBEDDED_JS: Record<string, string> = {',
  ];

  for (const [name, content] of Object.entries(jsFiles)) {
    lines.push(`  "${name}": \`${escapeString(content)}\`,`);
  }
  lines.push('};');
  lines.push('');
  lines.push('export const EMBEDDED_CSS: Record<string, string> = {');
  for (const [name, content] of Object.entries(cssFiles)) {
    lines.push(`  "${name}": \`${escapeString(content)}\`,`);
  }
  lines.push('};');
  lines.push('');

  // Ensure output directory exists
  mkdirSync(dirname(outputFile), { recursive: true });
  writeFileSync(outputFile, lines.join('\n'));

  const jsSize = Object.values(jsFiles).reduce((sum, c) => sum + c.length, 0);
  const cssSize = Object.values(cssFiles).reduce((sum, c) => sum + c.length, 0);
  console.log(`[embed-ui] Embedded ${Object.keys(jsFiles).length} JS files (${(jsSize / 1024).toFixed(1)}KB) and ${Object.keys(cssFiles).length} CSS files (${(cssSize / 1024).toFixed(1)}KB)`);
}

generate();
