import { ClickHouseConnection } from '../core/connection.js';
import fs from 'fs/promises';
import path from 'path';
import dotenv from 'dotenv';

// Load environment variables from the current directory
dotenv.config();

/**
 * @typedef {Object} ColumnInfo
 * @property {string} name - The name of the column
 * @property {string} type - The ClickHouse type of the column
 */

/**
 * Converts ClickHouse types to TypeScript types
 * @param {string} type - The ClickHouse type to convert
 * @returns {string} - The corresponding TypeScript type
 */
const clickhouseToTsType = (type) => {
  if (type.startsWith('Array(')) {
    const innerType = type.slice(6, -1);
    return `Array(${clickhouseToTsType(innerType)})`;
  }

  switch (type.toLowerCase()) {
    case 'string':
    case 'fixedstring':
      return 'String';
    case 'int8':
    case 'int16':
    case 'int32':
      return 'Int32';
    case 'int64':
      return 'Int64';
    case 'float32':
    case 'float64':
      return 'Float64';
    case 'datetime':
      return 'DateTime';
    case 'date':
      return 'Date';
    default:
      return 'String';
  }
};

/**
 * Generates TypeScript type definitions from the ClickHouse database schema
 * @param {string} outputPath - The file path where the type definitions will be written
 * @returns {Promise<void>}
 */
export async function generateTypes(outputPath) {
  const client = ClickHouseConnection.getClient();

  // Get all tables
  const tablesQuery = await client.query({
    query: 'SHOW TABLES',
    format: 'JSONEachRow'
  });
  const tables = await tablesQuery.json();

  let typeDefinitions = `// Generated by @hypequery/clickhouse
import { ColumnType } from '@hypequery/clickhouse';

export interface IntrospectedSchema {`;

  // Get columns for each table
  for (const table of tables) {
    const columnsQuery = await client.query({
      query: `DESCRIBE ${table.name}`,
      format: 'JSONEachRow'
    });
    const columns = await columnsQuery.json();

    typeDefinitions += `\n  ${table.name}: {`;
    for (const column of columns) {
      typeDefinitions += `\n    ${column.name}: '${clickhouseToTsType(column.type)}';`;
    }
    typeDefinitions += '\n  };';
  }

  typeDefinitions += '\n}\n';

  // Ensure the output directory exists
  const outputDir = path.dirname(path.resolve(outputPath));
  await fs.mkdir(outputDir, { recursive: true });

  // Write the file
  await fs.writeFile(path.resolve(outputPath), typeDefinitions);
} 