/**
 * Generate an example schema.ts with realistic sample tables.
 * Used when the user initializes without a ClickHouse connection.
 */
export function generateExampleSchemaTemplate(): string {
  return `// Generated by hypequery — example schema
// Replace this with real types by running: npx hypequery generate

export interface IntrospectedSchema {
  users: {
    id: number;
    name: string;
    email: string;
    created_at: string;
    plan: string;
  };
  orders: {
    id: number;
    user_id: number;
    amount: number;
    currency: string;
    status: string;
    created_at: string;
  };
  page_events: {
    event_id: string;
    user_id: number;
    page: string;
    action: string;
    timestamp: string;
  };
}
`;
}

/**
 * Generate a placeholder schema.ts for when user skips connection
 * but provides credentials (--skip-connection flag).
 */
export function generatePlaceholderSchemaTemplate(): string {
  return `// Generated by hypequery
// Run 'npx hypequery generate' after configuring your database connection

export interface IntrospectedSchema {
  // Your table types will appear here after generation
}
`;
}
