#!/usr/bin/env node
/**
 * Writes the package version into `src/version.ts` before every build.
 *
 * The version used to be read from `package.json` at import time. That made
 * merely importing `@hypequery/mcp` touch the filesystem, and it broke outright
 * under a bundler: webpack rewrites `import.meta.url`, so the `URL` handed to
 * `fs` came from another realm and Node rejected it with ERR_INVALID_ARG_TYPE.
 * A Cloud MCP gateway built with Next.js could not import this package at all.
 *
 * Generating the constant keeps the version honest — it cannot drift from the
 * manifest a release bumps — without any runtime lookup.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const packageRoot = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const manifestPath = path.join(packageRoot, 'package.json');
const targetPath = path.join(packageRoot, 'src', 'version.ts');

const { version } = JSON.parse(readFileSync(manifestPath, 'utf8'));
if (typeof version !== 'string' || version.length === 0) {
  throw new Error(`No version in ${manifestPath}`);
}

const contents = `// Generated by scripts/generate-version.mjs. Do not edit.
//
// Resolved at build time rather than read from package.json at import time, so
// importing this package touches no filesystem and survives bundling.
export const MCP_PACKAGE_VERSION = '${version}';
`;

// Only write on change, so a no-op build does not invalidate the turbo cache.
let current;
try {
  current = readFileSync(targetPath, 'utf8');
} catch {
  current = undefined;
}
if (current !== contents) {
  writeFileSync(targetPath, contents, 'utf8');
}
