/**
 * ClickHouse schema introspection to TypeScript types.
 *
 * Ported from `@hypequery/clickhouse/src/cli` so the CLI no longer has to
 * depend on the whole query-builder package to generate types. The copy over
 * there still backs the legacy `hypequery-generate-types` bin and the
 * `@hypequery/clickhouse/cli` subpath; this one is the living version.
 *
 * The one deliberate difference: there is no `ClickHouseConnection` fallback.
 * A client is always supplied by the caller, which is what let the query
 * builder drop off the CLI's module graph in the first place.
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { clickhouseToTsType } from './type-parsing.js';

/**
 * Minimal ClickHouse client surface the type generator needs. Both the HTTP
 * client and the embedded chDB session satisfy it.
 */
export interface TypeGenerationClickHouseClient {
  query(options: { query: string; format: 'JSONEachRow' }): Promise<{
    json(): Promise<Array<Record<string, string>>>;
  }>;
}

export interface GenerateTypesOptions {
  /** Only introspect these tables. Defaults to every table in the database. */
  includeTables?: string[];
  /** Skip these tables. Applied after `includeTables`. */
  excludeTables?: string[];
  /** Client used for introspection. */
  client: TypeGenerationClickHouseClient;
  /** Package name written into the generated file header. */
  generatedBy?: string;
  /** Append the historical usage-example comment block. */
  includeUsageExample?: boolean;
}

interface GeneratedTypeDefinitions {
  contents: string;
  tableNames: string[];
}

/**
 * Capitalize the first letter of a string.
 */
function capitalizeFirstLetter(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

async function describeTable(
  client: TypeGenerationClickHouseClient,
  tableName: string
): Promise<Array<Record<string, string>>> {
  const columnsQuery = await client.query({
    query: `DESCRIBE TABLE ${tableName}`,
    format: 'JSONEachRow',
  });

  return columnsQuery.json();
}

/**
 * Generates the TypeScript type definition source from a ClickHouse client.
 */
async function buildTypeDefinitions(
  client: TypeGenerationClickHouseClient,
  options: Omit<GenerateTypesOptions, 'client'> = {}
): Promise<GeneratedTypeDefinitions> {
  const {
    includeTables = [],
    excludeTables = [],
    generatedBy = 'hypequery',
    includeUsageExample = true,
  } = options;

  // Get all tables
  const tablesQuery = await client.query({
    query: 'SHOW TABLES',
    format: 'JSONEachRow',
  });
  let tables = await tablesQuery.json();

  // Filter tables if includeTables or excludeTables are specified
  if (includeTables.length > 0) {
    tables = tables.filter((table) => includeTables.includes(table.name));
  }

  if (excludeTables.length > 0) {
    tables = tables.filter((table) => !excludeTables.includes(table.name));
  }

  // If no tables remain after filtering, log a warning
  if (tables.length === 0) {
    console.warn('Warning: No tables match the filter criteria. Check your include/exclude options.');
  }

  let typeDefinitions = `// Generated by ${generatedBy}
// This file defines TypeScript types based on your ClickHouse database schema

/**
 * Schema interface for use with createQueryBuilder<IntrospectedSchema>()
 * The string literals represent ClickHouse data types for each column
 */
export interface IntrospectedSchema {`;

  // Get columns for each table
  for (const table of tables) {
    const columns = await describeTable(client, table.name);
    typeDefinitions += `\n  ${table.name}: {`;
    for (const column of columns) {
      const clickHouseType = column.type.replace(/'/g, "\\'"); // Escape single quotes, e.g. `DateTime('UTC')`
      typeDefinitions += `\n    '${column.name}': '${clickHouseType}';`;
    }
    typeDefinitions += '\n  };';
  }

  typeDefinitions += '\n}\n';

  // Also generate a type-safe record type for each table
  typeDefinitions += `\n// Type-safe record types for each table\n`;
  for (const table of tables) {
    const columns = await describeTable(client, table.name);

    typeDefinitions += `export interface ${capitalizeFirstLetter(table.name)}Record {`;
    for (const column of columns) {
      const tsType = clickhouseToTsType(column.type).replace(/'/g, '');
      typeDefinitions += `\n  '${column.name}': ${tsType};`;
    }
    typeDefinitions += '\n}\n\n';
  }

  if (includeUsageExample) {
    typeDefinitions += `
/**
 * Usage example:
 *
 * import { createQueryBuilder } from '@hypequery/clickhouse';
 * import { IntrospectedSchema } from './path-to-this-file';
 *
 * // Create a type-safe query builder
 * const db = createQueryBuilder<IntrospectedSchema>();
 *
 * // Now you have full type safety and autocomplete
 * const results = await db
 *   .table('${tables.length > 0 ? tables[0].name : 'table_name'}')
 *   .select(['column1', 'column2'])
 *   .where('column1', 'eq', 'value')
 *   .execute();
 */
`;
  }

  return {
    contents: typeDefinitions,
    tableNames: tables.map((table) => table.name),
  };
}

/**
 * Generates the TypeScript type definition source from a ClickHouse client.
 */
export async function generateTypeDefinitions(
  client: TypeGenerationClickHouseClient,
  options: Omit<GenerateTypesOptions, 'client'> = {}
): Promise<string> {
  const generated = await buildTypeDefinitions(client, options);
  return generated.contents;
}

/**
 * Generates TypeScript type definitions from the ClickHouse database schema and
 * writes them to `outputPath`, creating the containing directory if needed.
 * Returns the names of the tables represented in the generated file.
 */
export async function generateTypes(
  outputPath: string,
  options: GenerateTypesOptions
): Promise<string[]> {
  const { client, ...definitionOptions } = options;
  const generated = await buildTypeDefinitions(client, definitionOptions);

  // Ensure the output directory exists
  const outputDir = path.dirname(path.resolve(outputPath));
  await fs.mkdir(outputDir, { recursive: true });

  // Write the file
  await fs.writeFile(path.resolve(outputPath), generated.contents);

  return generated.tableNames;
}
