import { describe, expect, it } from 'vitest';
import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { generateTypeDefinitions, generateTypes } from './generate-types.js';
import type { TypeGenerationClickHouseClient } from './generate-types.js';

/**
 * Fake client driven by the SQL text rather than call order — the generator
 * describes each table twice (once for the schema interface, once for the
 * record interface), so an ordered mock would encode that as a contract.
 */
function fakeClient(tables: Record<string, Array<{ name: string; type: string }>>): TypeGenerationClickHouseClient {
  return {
    async query({ query }) {
      if (query === 'SHOW TABLES') {
        return { json: async () => Object.keys(tables).map((name) => ({ name })) };
      }

      const match = /^DESCRIBE TABLE (.+)$/.exec(query);
      const columns = match ? tables[match[1]] : undefined;

      if (!columns) {
        throw new Error(`Unexpected query: ${query}`);
      }

      return { json: async () => columns };
    },
  };
}

const usersAndEvents = {
  users: [
    { name: 'id', type: 'Int32' },
    { name: 'name', type: 'String' },
  ],
  events: [{ name: 'occurred_at', type: "DateTime('UTC')" }],
};

describe('generateTypeDefinitions', () => {
  it('generates schema and record interfaces from a provided client', async () => {
    const contents = await generateTypeDefinitions(fakeClient({ users: usersAndEvents.users }), {
      generatedBy: 'hypequery',
      includeUsageExample: false,
    });

    expect(contents).toContain('// Generated by hypequery');
    expect(contents).toContain('export interface IntrospectedSchema');
    expect(contents).toContain("'id': 'Int32';");
    expect(contents).toContain('export interface UsersRecord');
    expect(contents).toContain("'name': string;");
    expect(contents).not.toContain('Usage example');
  });

  it('escapes single quotes in ClickHouse type literals', async () => {
    const contents = await generateTypeDefinitions(fakeClient({ events: usersAndEvents.events }), {
      includeUsageExample: false,
    });

    // The literal has to survive being embedded in a single-quoted TS string.
    expect(contents).toContain("'occurred_at': 'DateTime(\\'UTC\\')';");
    expect(contents).toContain("'occurred_at': string;");
  });

  it('honours includeTables', async () => {
    const contents = await generateTypeDefinitions(fakeClient(usersAndEvents), {
      includeTables: ['users'],
      includeUsageExample: false,
    });

    expect(contents).toContain('export interface UsersRecord');
    expect(contents).not.toContain('export interface EventsRecord');
  });

  it('honours excludeTables', async () => {
    const contents = await generateTypeDefinitions(fakeClient(usersAndEvents), {
      excludeTables: ['events'],
      includeUsageExample: false,
    });

    expect(contents).toContain('export interface UsersRecord');
    expect(contents).not.toContain('export interface EventsRecord');
  });

  it('appends the usage example by default', async () => {
    const contents = await generateTypeDefinitions(fakeClient({ users: usersAndEvents.users }));

    expect(contents).toContain('Usage example');
    expect(contents).toContain(".table('users')");
  });
});

describe('generateTypes', () => {
  it('writes the definitions, creating the output directory', async () => {
    const dir = await mkdtemp(path.join(tmpdir(), 'hq-typegen-'));
    // `nested/` does not exist yet — the generator is responsible for it.
    const outputPath = path.join(dir, 'nested', 'schema.ts');

    const generatedTables = await generateTypes(outputPath, {
      client: fakeClient(usersAndEvents),
      generatedBy: 'hypequery',
      includeUsageExample: false,
      includeTables: ['users', 'users', 'missing'],
    });

    const written = await readFile(outputPath, 'utf8');
    expect(written).toContain('export interface IntrospectedSchema');
    expect(written).toContain('export interface UsersRecord');
    expect(written).not.toContain('export interface EventsRecord');
    expect(generatedTables).toEqual(['users']);
  });
});
