import { ClickHouseConnection } from '../core/connection.js';
import fs from 'fs/promises';
import path from 'path';
import dotenv from 'dotenv';
import { clickhouseToTsType } from './type-parsing.js';

export { clickhouseToTsType } from './type-parsing.js';

// Load environment variables from the current directory
dotenv.config();

/**
 * @typedef {Object} ColumnInfo
 * @property {string} name - The name of the column
 * @property {string} type - The ClickHouse type of the column
 */

/**
 * @typedef {Object} GenerateTypesOptions
 * @property {string[]} [includeTables] - List of tables to include
 * @property {string[]} [excludeTables] - List of tables to exclude
 * @property {object} [client] - ClickHouse client to use instead of ClickHouseConnection
 * @property {string} [generatedBy] - Package name to include in the generated file header
 * @property {boolean} [includeUsageExample] - Whether to append the historical usage example
 */

/**
 * Generates TypeScript type definitions from the ClickHouse database schema
 * @param {string} outputPath - The file path where the type definitions will be written
 * @param {GenerateTypesOptions} [options] - Options for type generation
 * @returns {Promise<void>}
 */
export async function generateTypes(outputPath, options = {}) {
  const client = options.client || ClickHouseConnection.getClient();
  const typeDefinitions = await generateTypeDefinitions(client, options);

  // Ensure the output directory exists
  const outputDir = path.dirname(path.resolve(outputPath));
  await fs.mkdir(outputDir, { recursive: true });

  // Write the file
  await fs.writeFile(path.resolve(outputPath), typeDefinitions);
}

/**
 * Generates TypeScript type definition contents from a ClickHouse client.
 * @param {object} client - ClickHouse client with a query method
 * @param {GenerateTypesOptions} [options] - Options for type generation
 * @returns {Promise<string>}
 */
export async function generateTypeDefinitions(client, options = {}) {
  const {
    includeTables = [],
    excludeTables = [],
    generatedBy = '@hypequery/clickhouse',
    includeUsageExample = true,
  } = options;

  // Get all tables
  const tablesQuery = await client.query({
    query: 'SHOW TABLES',
    format: 'JSONEachRow'
  });
  let tables = await tablesQuery.json();

  // Filter tables if includeTables or excludeTables are specified
  if (includeTables.length > 0) {
    tables = tables.filter(table => includeTables.includes(table.name));
  }

  if (excludeTables.length > 0) {
    tables = tables.filter(table => !excludeTables.includes(table.name));
  }

  // If no tables remain after filtering, log a warning
  if (tables.length === 0) {
    console.warn('Warning: No tables match the filter criteria. Check your include/exclude options.');
  }

  let typeDefinitions = `// Generated by ${generatedBy}
// This file defines TypeScript types based on your ClickHouse database schema

/**
 * Schema interface for use with createQueryBuilder<IntrospectedSchema>()
 * The string literals represent ClickHouse data types for each column
 */
export interface IntrospectedSchema {`;

  // Get columns for each table
  for (const table of tables) {
    const columnsQuery = await client.query({
      query: `DESCRIBE TABLE ${table.name}`,
      format: 'JSONEachRow'
    });
    const columns = await columnsQuery.json();
    typeDefinitions += `\n  ${table.name}: {`;
    for (const column of columns) {
      const clickHouseType = column.type.replace(/'/g, "\\'"); // Escape single quotes, e.g. `DateTime('UTC')`
      typeDefinitions += `\n    '${column.name}': '${clickHouseType}';`;
    }
    typeDefinitions += '\n  };';
  }

  typeDefinitions += '\n}\n';

  // Also generate a type-safe record type for each table
  typeDefinitions += `\n// Type-safe record types for each table\n`;
  for (const table of tables) {
    const columnsQuery = await client.query({
      query: `DESCRIBE TABLE ${table.name}`,
      format: 'JSONEachRow'
    });
    const columns = await columnsQuery.json();

    typeDefinitions += `export interface ${capitalizeFirstLetter(table.name)}Record {`;
    for (const column of columns) {
      const tsType = clickhouseToTsType(column.type).replace(/'/g, '');
      typeDefinitions += `\n  '${column.name}': ${tsType};`;
    }
    typeDefinitions += '\n}\n\n';
  }

  if (includeUsageExample) {
    typeDefinitions += `
/**
 * Usage example:
 * 
 * import { createQueryBuilder } from '@hypequery/clickhouse';
 * import { IntrospectedSchema } from './path-to-this-file';
 * 
 * // Create a type-safe query builder
 * const db = createQueryBuilder<IntrospectedSchema>();
 * 
 * // Now you have full type safety and autocomplete
 * const results = await db
 *   .table('${tables.length > 0 ? tables[0].name : 'table_name'}')
 *   .select(['column1', 'column2'])
 *   .where('column1', 'eq', 'value')
 *   .execute();
 */
`;
  }

  return typeDefinitions;
}

/**
 * Capitalize the first letter of a string
 * @param {string} str - The string to capitalize
 * @returns {string} - The capitalized string
 */
function capitalizeFirstLetter(str) {
  return str.charAt(0).toUpperCase() + str.slice(1);
} 
