"""Request identifiers: the server's authoritative id and a caller's correlation id.

The authoritative id is generated by the HTTP security profile's middleware and
kept under a key only this package holds. A caller's own id is never
authoritative; it is echoed only after passing the same grammar and bound as
TypeScript serve.
"""

from __future__ import annotations

import re
import secrets

from fastapi import Request

from .utils.scope_slot import ScopeSlot

#: TypeScript serve's bound and grammar for an external correlation id: small,
#: printable ASCII that cannot split a header or forge a log line.
MAX_CORRELATION_ID_BYTES = 200
_CORRELATION_ID = re.compile(r"[A-Za-z0-9][A-Za-z0-9._:/-]*")
#: Only this package holds the slot, so no middleware or handler that does not
#: import it can plant a request id where `request_id()` reads one.
REQUEST_ID_SLOT: ScopeSlot[str] = ScopeSlot(str)


def validate_correlation_id(value: str | None) -> str | None:
    """A caller's correlation id if it is safe to echo and log, else None."""

    if value is None:
        return None
    candidate = value.strip()
    if len(candidate.encode("utf-8")) > MAX_CORRELATION_ID_BYTES:
        return None
    return candidate if _CORRELATION_ID.fullmatch(candidate) else None


def request_id(request: Request) -> str | None:
    """The authoritative, server-generated id of *request*, when installed."""

    return REQUEST_ID_SLOT.get(request.scope)


def ensure_request_id(request: Request) -> str:
    """Reuse the profile's id, or establish one for a standalone error path."""

    return REQUEST_ID_SLOT.setdefault(request.scope, lambda: secrets.token_hex(16))
