import { dirname, relative, resolve } from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import type { Snapshot, SnapshotColumn, SnapshotTable } from '@hypequery/schema';
import {
  isIntegerLiteral,
  matchTypeCall,
  unquoteClickHouseString,
  unwrapType,
} from './clickhouse-type-utils.js';

interface EmitSchemaFileOptions {
  snapshot: Snapshot;
  outputPath: string;
}

export async function writeSchemaFileFromSnapshot(options: EmitSchemaFileOptions) {
  const outputPath = resolve(process.cwd(), options.outputPath);
  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, renderSchemaFile(options.snapshot), 'utf8');

  return outputPath;
}

export function renderSchemaFile(snapshot: Snapshot) {
  const usesSql = snapshot.tables.some(table => table.columns.some(column => column.default?.kind === 'sql'));
  const imports = usesSql
    ? "import { column, defineSchema, defineTable, sql } from '@hypequery/schema';"
    : "import { column, defineSchema, defineTable } from '@hypequery/schema';";

  const lines = [
    '// Generated by hypequery pull.',
    '// Review TODO comments before using this as the long-term schema source of truth.',
    imports,
    '',
    'export default defineSchema({',
    '  tables: [',
    ...snapshot.tables.flatMap(renderTable),
    '  ],',
    '});',
    '',
  ];

  return lines.join('\n');
}

function renderTable(table: SnapshotTable): string[] {
  return [
    `    defineTable(${quote(table.name)}, {`,
    '      columns: {',
    ...table.columns.map(column => `        ${renderPropertyKey(column.name)}: ${renderColumn(column)},`),
    '      },',
    '      engine: {',
    `        type: ${quote(table.engine.type)},`,
    ...renderExpressionList('orderBy', table.engine.orderBy),
    ...renderExpressionList('primaryKey', table.engine.primaryKey),
    ...(table.engine.partitionBy ? [`        partitionBy: ${quote(table.engine.partitionBy)},`] : []),
    '      },',
    ...renderSettings(table.settings),
    '    }),',
  ];
}

function renderColumn(column: SnapshotColumn) {
  const defaultExpression = column.default?.kind === 'sql'
    ? `.default(sql\`${escapeTemplate(column.default.value)}\`)`
    : column.default?.kind === 'literal'
      ? `.default(${JSON.stringify(column.default.value)})`
      : '';

  return `${renderColumnType(column.type)}${defaultExpression}`;
}

function renderColumnType(type: string): string {
  const nullable = unwrapType(type, 'Nullable');
  if (nullable) {
    return `column.Nullable(${renderNestedType(nullable)})`;
  }

  const lowCardinality = unwrapType(type, 'LowCardinality');
  if (lowCardinality) {
    return `column.LowCardinality(${renderNestedType(lowCardinality)})`;
  }

  return renderBaseColumnType(type);
}

function renderNestedType(type: string): string {
  const nullable = unwrapType(type, 'Nullable');
  if (nullable) {
    return `{ kind: 'nullable', inner: ${renderRawColumnType(nullable)} }`;
  }

  const lowCardinality = unwrapType(type, 'LowCardinality');
  if (lowCardinality) {
    return `{ kind: 'low_cardinality', inner: ${renderRawColumnType(lowCardinality)} }`;
  }

  const base = renderSupportedBaseColumnType(type);
  return base ?? quote(type);
}

function renderBaseColumnType(type: string): string {
  return renderSupportedBaseColumnType(type) ??
    `column.Raw(${quote(type)}) /* TODO: Review unsupported ClickHouse type. */`;
}

function renderSupportedBaseColumnType(type: string): string | null {
  const fixedString = matchTypeCall(type, 'FixedString');
  if (fixedString && fixedString.length === 1 && isIntegerLiteral(fixedString[0])) {
    return `column.FixedString(${fixedString[0]})`;
  }

  const decimal = matchTypeCall(type, 'Decimal');
  if (decimal && decimal.length === 2 && decimal.every(isIntegerLiteral)) {
    return `column.Decimal(${decimal[0]}, ${decimal[1]})`;
  }

  if (type === 'DateTime') {
    return 'column.DateTime()';
  }

  const dateTime = matchTypeCall(type, 'DateTime');
  if (dateTime) {
    return `column.DateTime(${quote(unquoteClickHouseString(dateTime[0]))})`;
  }

  const dateTime64 = matchTypeCall(type, 'DateTime64');
  if (dateTime64 && dateTime64.length >= 1 && isIntegerLiteral(dateTime64[0])) {
    return dateTime64.length === 1
      ? `column.DateTime64(${dateTime64[0]})`
      : `column.DateTime64(${dateTime64[0]}, ${quote(unquoteClickHouseString(dateTime64[1]))})`;
  }

  if (SIMPLE_COLUMN_TYPES.has(type)) {
    return `column.${type}()`;
  }

  return null;
}

function renderRawColumnType(type: string) {
  return `{ kind: 'named', name: ${quote(type)} }`;
}

const SIMPLE_COLUMN_TYPES = new Set([
  'Int8',
  'Int16',
  'Int32',
  'Int64',
  'Int128',
  'Int256',
  'UInt8',
  'UInt16',
  'UInt32',
  'UInt64',
  'UInt128',
  'UInt256',
  'Float32',
  'Float64',
  'Bool',
  'Boolean',
  'String',
  'Date',
  'Date32',
  'UUID',
  'IPv4',
  'IPv6',
  'JSON',
]);

function renderExpressionList(name: string, values: string[]) {
  if (values.length === 0) {
    return [];
  }

  return [`        ${name}: [${values.map(quote).join(', ')}],`];
}

function renderSettings(settings: Record<string, string>) {
  const entries = Object.entries(settings);
  if (entries.length === 0) {
    return [];
  }

  return [
    '      settings: {',
    ...entries.map(([key, value]) => `        ${renderPropertyKey(key)}: ${quote(value)},`),
    '      },',
  ];
}

function renderPropertyKey(name: string) {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : quote(name);
}

function quote(value: string) {
  return JSON.stringify(value);
}

function escapeTemplate(value: string) {
  return value.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

export function relativeSchemaPath(outputPath: string) {
  return relative(process.cwd(), resolve(process.cwd(), outputPath));
}
