import type { Metadata } from 'next';
import { ClickhousePillarPage } from '@/components/clickhouse-pillar-page';
import { absoluteUrl } from '@/lib/site';

export const metadata: Metadata = {
  title: 'ClickHouse Product Analytics — TypeScript Event Tracking & Querying | hypequery',
  description:
    'Build product analytics on ClickHouse in TypeScript. hypequery gives you typed event queries, funnel analysis, retention metrics, and typed APIs for your analytics stack.',
  alternates: {
    canonical: absoluteUrl('/clickhouse-product-analytics'),
  },
  openGraph: {
    type: 'website',
    url: absoluteUrl('/clickhouse-product-analytics'),
    title: 'ClickHouse Product Analytics — TypeScript Event Tracking & Querying | hypequery',
    description:
      'Build product analytics on ClickHouse in TypeScript. hypequery gives you typed event queries, funnel analysis, retention metrics, and typed APIs for your analytics stack.',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'ClickHouse Product Analytics — TypeScript Event Tracking & Querying | hypequery',
    description:
      'Build product analytics on ClickHouse in TypeScript. hypequery gives you typed event queries, funnel analysis, retention metrics, and typed APIs for your analytics stack.',
  },
};

const eventQueryCode = `// Generated by: npx @hypequery/cli generate --output ./schema.ts
// Schema reflects actual ClickHouse table structure
import { createQueryBuilder } from '@hypequery/clickhouse';
import type { Schema } from './schema';

const db = createQueryBuilder<Schema>({ /* connection config */ });

// Daily active users — uniq() is ClickHouse-native
const dau = await db
  .table('events')
  .select(
    'toStartOfDay(created_at) as date',
    'uniq(user_id) as active_users',
    'count() as event_count',
  )
  .where('created_at', 'gte', '2026-04-01')
  .where('created_at', 'lte', '2026-04-30')
  .where('tenant_id', 'eq', tenantId)
  .groupBy('date')
  .orderBy('date', 'ASC')
  .execute();

// Funnel — windowFunnel is ClickHouse-native
const funnelQuery = await db
  .table('events')
  .select(
    'user_id',
    \`windowFunnel(86400)('created_at',
      name = 'signup',
      name = 'onboarding_complete',
      name = 'first_purchase'
    ) AS funnel_step\`,
  )
  .where('created_at', 'gte', '2026-04-01')
  .where('tenant_id', 'eq', tenantId)
  .groupBy('user_id')
  .execute();`;

const analyticsApiCode = `// analytics/product-analytics.ts
import { initServe } from '@hypequery/serve';
import { db } from '@/lib/clickhouse';
import { z } from 'zod';

const { query, serve } = initServe({
  context: (req) => ({
    db,
    tenantId: req.headers['x-tenant-id'] as string,
  }),
});

export const dau = query({
  input: z.object({ startDate: z.string(), endDate: z.string() }),
  query: ({ ctx, input }) =>
    ctx.db
      .table('events')
      .select('toStartOfDay(created_at) as date', 'uniq(user_id) as active_users')
      .where('tenant_id', 'eq', ctx.tenantId)
      .where('created_at', 'gte', input.startDate)
      .where('created_at', 'lte', input.endDate)
      .groupBy('date')
      .orderBy('date', 'ASC')
      .execute(),
});

export const retention = query({
  input: z.object({ cohortDate: z.string(), days: z.number().int().min(1).max(90) }),
  query: ({ ctx, input }) =>
    ctx.db
      .table('events')
      .select(
        'toDate(created_at) as activity_date',
        'uniq(user_id) as retained_users',
        \`dateDiff('day', '\${input.cohortDate}', toDate(created_at)) as day_offset\`,
      )
      .where('tenant_id', 'eq', ctx.tenantId)
      .where(
        'user_id',
        'in',
        ctx.db
          .table('events')
          .select('user_id')
          .where('toDate(created_at)', 'eq', input.cohortDate)
          .where('tenant_id', 'eq', ctx.tenantId),
      )
      .where('created_at', 'lte', \`addDays('\${input.cohortDate}', \${input.days})\`)
      .groupBy('activity_date', 'day_offset')
      .orderBy('day_offset', 'ASC')
      .execute(),
});

export const api = serve({ queries: { dau, retention } });`;

export default function ClickHouseProductAnalyticsPage() {
  return (
    <ClickhousePillarPage
      eyebrow="ClickHouse Product Analytics"
      title="Build product analytics on ClickHouse with TypeScript"
      description="Product analytics tables are wide, high-cardinality, and queried in many ways — DAU, funnels, retention, segmentation. hypequery gives TypeScript teams schema-generated types for event tables and a composable query layer for the analytics patterns that matter."
      primaryCta={{ href: '/docs/quick-start', label: 'Open quick start' }}
      secondaryCta={{ href: '/clickhouse-analytics', label: 'See the analytics layer overview' }}
      stats={[
        { label: 'Key aggregations', value: 'uniq, windowFunnel, retention' },
        { label: 'Schema source', value: 'Generated from live ClickHouse' },
        { label: 'Best for', value: 'Product and SaaS analytics teams' },
      ]}
      problems={[
        {
          title: 'Event tables have wide schemas that drift constantly',
          copy:
            'Product analytics tables — events, sessions, funnels — have high cardinality and many columns that grow as new event types are added. Hand-written TypeScript interfaces for them are massive, tedious, and inevitably drift from the actual schema.',
        },
        {
          title: 'Funnel and retention queries are hard to make reusable',
          copy:
            'Funnel analysis using windowFunnel and retention using cohort filters are complex ClickHouse-specific SQL patterns. Wrapping them in a type-safe, composable layer makes them reusable across product and data teams instead of reimplemented per dashboard.',
        },
        {
          title: 'Internal and customer-facing analytics need the same query logic',
          copy:
            'Serving the same product analytics to internal dashboards and customer-facing UIs typically results in two separate data layers with duplicated query logic. A shared analytics layer with route-level delivery paths solves this without code duplication.',
        },
      ]}
      solutionSection={{
        eyebrow: 'Event queries',
        title: 'Schema-generated types for events and ClickHouse-native aggregations',
        description:
          'The bottleneck in product analytics on ClickHouse is rarely query speed — it is the TypeScript layer around the queries. Generating types from the live schema ensures the types reflect reality, not a stale hand-written copy.',
        bullets: [
          'Run npx @hypequery/cli generate to introspect your events table and emit TypeScript types',
          'Use uniq() for distinct user counts — ClickHouse HyperLogLog, not COUNT(DISTINCT)',
          'Use windowFunnel() for ordered funnel analysis within a time window',
          'Compose filters (tenant, date range, event type) using typed .where() calls',
          'Reuse the same query definitions across internal and customer-facing surfaces',
        ],
        codePanel: {
          eyebrow: 'Event queries',
          title: 'Typed DAU and funnel queries using ClickHouse-native aggregations',
          description:
            'Schema-generated types mean the select column names and their TypeScript types are verified at compile time, not discovered at runtime when a dashboard breaks.',
          code: eventQueryCode,
        },
      }}
      implementationSection={{
        eyebrow: 'Analytics API',
        title: 'Serve DAU, retention, and funnel metrics from a shared API layer',
        description:
          'Once product analytics queries are defined as named contracts, the same definitions can serve an internal analytics dashboard, a customer-facing analytics page, and a scheduled report pipeline — without duplicating query logic.',
        paragraphs: [
          'The key insight is that context-level tenant isolation — applied once in initServe — means every analytics query is safe to expose over HTTP without re-verifying the tenant filter per endpoint.',
          'For teams building self-serve product analytics for customers, this is the foundation: one analytics definition, tenant-isolated by default, deliverable to multiple surfaces.',
        ],
        codePanel: {
          eyebrow: 'Product analytics API',
          title: 'DAU and retention as typed, tenant-isolated endpoints',
          description:
            'The tenant isolation lives in the context, not in each query. Adding a new metric does not require remembering to add the tenant filter — it is structural.',
          code: analyticsApiCode,
        },
      }}
      searchIntentCards={[
        {
          title: 'ClickHouse product analytics TypeScript',
          copy:
            'TypeScript product analytics on ClickHouse starts with schema generation. Once the event table types are accurate, DAU, funnel, and retention queries can be written with full compile-time safety.',
        },
        {
          title: 'ClickHouse event tracking queries',
          copy:
            'Event tracking in ClickHouse works well when the query layer distinguishes between ClickHouse-native aggregations (uniq, windowFunnel) and generic patterns. hypequery preserves access to both.',
        },
        {
          title: 'ClickHouse funnel analysis TypeScript',
          copy:
            'windowFunnel is a ClickHouse-native function for ordered funnel analysis within a configurable time window. Wrapping it in a typed, reusable contract prevents fragile funnel SQL from being duplicated across dashboards.',
        },
        {
          title: 'ClickHouse retention metrics',
          copy:
            'Cohort retention on ClickHouse requires a subquery for the cohort definition and date arithmetic. A typed analytics layer makes that pattern reusable with configurable cohort date and day offset.',
        },
      ]}
      readingLinks={[
        {
          href: '/clickhouse-analytics',
          title: 'ClickHouse Analytics',
          description: 'The broader analytics layer architecture that product analytics builds on.',
        },
        {
          href: '/clickhouse-saas-analytics',
          title: 'ClickHouse SaaS Analytics',
          description: 'Expose product analytics to customers in a SaaS product with tenant isolation.',
        },
        {
          href: '/clickhouse-dashboard',
          title: 'ClickHouse Dashboard',
          description: 'Wire product analytics queries to React dashboard components with typed hooks.',
        },
        {
          href: '/blog/turn-your-clickhouse-schema-into-a-type-safe-analytics-layer-in-5-minutes',
          title: 'Turn your ClickHouse schema into a type-safe analytics layer',
          description: 'Step-by-step: from schema generation to working analytics hooks.',
        },
      ]}
      relatedPillars={[
        { href: '/clickhouse-analytics', label: 'ClickHouse Analytics' },
        { href: '/clickhouse-saas-analytics', label: 'ClickHouse SaaS Analytics' },
        { href: '/clickhouse-dashboard', label: 'ClickHouse Dashboard' },
        { href: '/clickhouse-real-time-analytics', label: 'ClickHouse Real-Time Analytics' },
      ]}
      nextStep={{
        eyebrow: 'Next step',
        title: 'Generate your events schema and write the first typed analytics query',
        description:
          'Schema generation is the foundation of typed product analytics. Once your events table is reflected in TypeScript, DAU, funnel, and retention queries all follow the same composable pattern.',
        primaryCta: { href: '/docs/quick-start', label: 'Open quick start' },
        secondaryCta: { href: '/clickhouse-analytics', label: 'See analytics layer overview' },
      }}
    />
  );
}
