// @ts-nocheck
import * as __fd_glob_65 from "../docs/reference/api/types.mdx?collection=docs"
import * as __fd_glob_64 from "../docs/reference/api/runtime.mdx?collection=docs"
import * as __fd_glob_63 from "../docs/reference/api/react.mdx?collection=docs"
import * as __fd_glob_62 from "../docs/reference/api/query.mdx?collection=docs"
import * as __fd_glob_61 from "../docs/reference/api/query-builder.mdx?collection=docs"
import * as __fd_glob_60 from "../docs/reference/api/cli.mdx?collection=docs"
import * as __fd_glob_59 from "../docs/reference/packages.mdx?collection=docs"
import * as __fd_glob_58 from "../docs/reference/inside-the-query-builder.mdx?collection=docs"
import * as __fd_glob_57 from "../docs/reference/connection.mdx?collection=docs"
import * as __fd_glob_56 from "../docs/reference/clickhouse-behavior.mdx?collection=docs"
import * as __fd_glob_55 from "../docs/mcp/tools.mdx?collection=docs"
import * as __fd_glob_54 from "../docs/mcp/safety.mdx?collection=docs"
import * as __fd_glob_53 from "../docs/mcp/programmatic.mdx?collection=docs"
import * as __fd_glob_52 from "../docs/mcp/overview.mdx?collection=docs"
import * as __fd_glob_51 from "../docs/mcp/configuration.mdx?collection=docs"
import * as __fd_glob_50 from "../docs/mcp/clients.mdx?collection=docs"
import * as __fd_glob_49 from "../docs/react/using-queries.mdx?collection=docs"
import * as __fd_glob_48 from "../docs/react/getting-started.mdx?collection=docs"
import * as __fd_glob_47 from "../docs/react/advanced-patterns.mdx?collection=docs"
import * as __fd_glob_46 from "../docs/query-building/where.mdx?collection=docs"
import * as __fd_glob_45 from "../docs/query-building/time-functions.mdx?collection=docs"
import * as __fd_glob_44 from "../docs/query-building/subqueries-ctes.mdx?collection=docs"
import * as __fd_glob_43 from "../docs/query-building/sql-expressions.mdx?collection=docs"
import * as __fd_glob_42 from "../docs/query-building/select.mdx?collection=docs"
import * as __fd_glob_41 from "../docs/query-building/ordering.mdx?collection=docs"
import * as __fd_glob_40 from "../docs/query-building/joins.mdx?collection=docs"
import * as __fd_glob_39 from "../docs/query-building/join-relationships.mdx?collection=docs"
import * as __fd_glob_38 from "../docs/query-building/helper-methods.mdx?collection=docs"
import * as __fd_glob_37 from "../docs/query-building/caching.mdx?collection=docs"
import * as __fd_glob_36 from "../docs/query-building/basics.mdx?collection=docs"
import * as __fd_glob_35 from "../docs/query-building/aggregation.mdx?collection=docs"
import * as __fd_glob_34 from "../docs/query-building/advanced-filtering.mdx?collection=docs"
import * as __fd_glob_33 from "../docs/datasets/time-grains.mdx?collection=docs"
import * as __fd_glob_32 from "../docs/datasets/serve-integration.mdx?collection=docs"
import * as __fd_glob_31 from "../docs/datasets/overview.mdx?collection=docs"
import * as __fd_glob_30 from "../docs/datasets/multi-tenancy.mdx?collection=docs"
import * as __fd_glob_29 from "../docs/datasets/metrics.mdx?collection=docs"
import * as __fd_glob_28 from "../docs/datasets/measures.mdx?collection=docs"
import * as __fd_glob_27 from "../docs/datasets/filters.mdx?collection=docs"
import * as __fd_glob_26 from "../docs/datasets/execution.mdx?collection=docs"
import * as __fd_glob_25 from "../docs/datasets/dimensions.mdx?collection=docs"
import * as __fd_glob_24 from "../docs/datasets/defining-datasets.mdx?collection=docs"
import * as __fd_glob_23 from "../docs/why-hypequery.mdx?collection=docs"
import * as __fd_glob_22 from "../docs/vite.mdx?collection=docs"
import * as __fd_glob_21 from "../docs/schemas.mdx?collection=docs"
import * as __fd_glob_20 from "../docs/runtime-features.mdx?collection=docs"
import * as __fd_glob_19 from "../docs/roadmap.mdx?collection=docs"
import * as __fd_glob_18 from "../docs/re-using-queries.mdx?collection=docs"
import * as __fd_glob_17 from "../docs/rate-limiting.mdx?collection=docs"
import * as __fd_glob_16 from "../docs/quick-start.mdx?collection=docs"
import * as __fd_glob_15 from "../docs/observability.mdx?collection=docs"
import * as __fd_glob_14 from "../docs/nodejs.mdx?collection=docs"
import * as __fd_glob_13 from "../docs/nextjs.mdx?collection=docs"
import * as __fd_glob_12 from "../docs/multi-tenancy.mdx?collection=docs"
import * as __fd_glob_11 from "../docs/introduction.mdx?collection=docs"
import * as __fd_glob_10 from "../docs/http-openapi.mdx?collection=docs"
import * as __fd_glob_9 from "../docs/fetch.mdx?collection=docs"
import * as __fd_glob_8 from "../docs/faq.mdx?collection=docs"
import * as __fd_glob_7 from "../docs/embedded-runtime.mdx?collection=docs"
import * as __fd_glob_6 from "../docs/cors.mdx?collection=docs"
import * as __fd_glob_5 from "../docs/core-concepts.mdx?collection=docs"
import * as __fd_glob_4 from "../docs/changelog.mdx?collection=docs"
import * as __fd_glob_3 from "../docs/authentication.mdx?collection=docs"
import { default as __fd_glob_2 } from "../docs/reference/api/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../docs/query-building/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "docs", {"meta.json": __fd_glob_0, "query-building/meta.json": __fd_glob_1, "reference/api/meta.json": __fd_glob_2, }, {"authentication.mdx": __fd_glob_3, "changelog.mdx": __fd_glob_4, "core-concepts.mdx": __fd_glob_5, "cors.mdx": __fd_glob_6, "embedded-runtime.mdx": __fd_glob_7, "faq.mdx": __fd_glob_8, "fetch.mdx": __fd_glob_9, "http-openapi.mdx": __fd_glob_10, "introduction.mdx": __fd_glob_11, "multi-tenancy.mdx": __fd_glob_12, "nextjs.mdx": __fd_glob_13, "nodejs.mdx": __fd_glob_14, "observability.mdx": __fd_glob_15, "quick-start.mdx": __fd_glob_16, "rate-limiting.mdx": __fd_glob_17, "re-using-queries.mdx": __fd_glob_18, "roadmap.mdx": __fd_glob_19, "runtime-features.mdx": __fd_glob_20, "schemas.mdx": __fd_glob_21, "vite.mdx": __fd_glob_22, "why-hypequery.mdx": __fd_glob_23, "datasets/defining-datasets.mdx": __fd_glob_24, "datasets/dimensions.mdx": __fd_glob_25, "datasets/execution.mdx": __fd_glob_26, "datasets/filters.mdx": __fd_glob_27, "datasets/measures.mdx": __fd_glob_28, "datasets/metrics.mdx": __fd_glob_29, "datasets/multi-tenancy.mdx": __fd_glob_30, "datasets/overview.mdx": __fd_glob_31, "datasets/serve-integration.mdx": __fd_glob_32, "datasets/time-grains.mdx": __fd_glob_33, "query-building/advanced-filtering.mdx": __fd_glob_34, "query-building/aggregation.mdx": __fd_glob_35, "query-building/basics.mdx": __fd_glob_36, "query-building/caching.mdx": __fd_glob_37, "query-building/helper-methods.mdx": __fd_glob_38, "query-building/join-relationships.mdx": __fd_glob_39, "query-building/joins.mdx": __fd_glob_40, "query-building/ordering.mdx": __fd_glob_41, "query-building/select.mdx": __fd_glob_42, "query-building/sql-expressions.mdx": __fd_glob_43, "query-building/subqueries-ctes.mdx": __fd_glob_44, "query-building/time-functions.mdx": __fd_glob_45, "query-building/where.mdx": __fd_glob_46, "react/advanced-patterns.mdx": __fd_glob_47, "react/getting-started.mdx": __fd_glob_48, "react/using-queries.mdx": __fd_glob_49, "mcp/clients.mdx": __fd_glob_50, "mcp/configuration.mdx": __fd_glob_51, "mcp/overview.mdx": __fd_glob_52, "mcp/programmatic.mdx": __fd_glob_53, "mcp/safety.mdx": __fd_glob_54, "mcp/tools.mdx": __fd_glob_55, "reference/clickhouse-behavior.mdx": __fd_glob_56, "reference/connection.mdx": __fd_glob_57, "reference/inside-the-query-builder.mdx": __fd_glob_58, "reference/packages.mdx": __fd_glob_59, "reference/api/cli.mdx": __fd_glob_60, "reference/api/query-builder.mdx": __fd_glob_61, "reference/api/query.mdx": __fd_glob_62, "reference/api/react.mdx": __fd_glob_63, "reference/api/runtime.mdx": __fd_glob_64, "reference/api/types.mdx": __fd_glob_65, });