// @ts-nocheck
import * as __fd_glob_65 from "../docs/standalone-query-builder/query-building/where.mdx?collection=docs"
import * as __fd_glob_64 from "../docs/standalone-query-builder/query-building/time-functions.mdx?collection=docs"
import * as __fd_glob_63 from "../docs/standalone-query-builder/query-building/subqueries-ctes.mdx?collection=docs"
import * as __fd_glob_62 from "../docs/standalone-query-builder/query-building/sql-expressions.mdx?collection=docs"
import * as __fd_glob_61 from "../docs/standalone-query-builder/query-building/select.mdx?collection=docs"
import * as __fd_glob_60 from "../docs/standalone-query-builder/query-building/ordering.mdx?collection=docs"
import * as __fd_glob_59 from "../docs/standalone-query-builder/query-building/joins.mdx?collection=docs"
import * as __fd_glob_58 from "../docs/standalone-query-builder/query-building/join-relationships.mdx?collection=docs"
import * as __fd_glob_57 from "../docs/standalone-query-builder/query-building/helper-methods.mdx?collection=docs"
import * as __fd_glob_56 from "../docs/standalone-query-builder/query-building/basics.mdx?collection=docs"
import * as __fd_glob_55 from "../docs/standalone-query-builder/query-building/aggregation.mdx?collection=docs"
import * as __fd_glob_54 from "../docs/standalone-query-builder/query-building/advanced.mdx?collection=docs"
import * as __fd_glob_53 from "../docs/standalone-query-builder/query-building/advanced-filtering.mdx?collection=docs"
import * as __fd_glob_52 from "../docs/reference/types.mdx?collection=docs"
import * as __fd_glob_51 from "../docs/reference/serve.mdx?collection=docs"
import * as __fd_glob_50 from "../docs/reference/react.mdx?collection=docs"
import * as __fd_glob_49 from "../docs/reference/query-builder.mdx?collection=docs"
import * as __fd_glob_48 from "../docs/reference/packages.mdx?collection=docs"
import * as __fd_glob_47 from "../docs/reference/connection.mdx?collection=docs"
import * as __fd_glob_46 from "../docs/reference/cli.mdx?collection=docs"
import * as __fd_glob_45 from "../docs/standalone-query-builder/when-to-use.mdx?collection=docs"
import * as __fd_glob_44 from "../docs/standalone-query-builder/standalone-query-builder.mdx?collection=docs"
import * as __fd_glob_43 from "../docs/standalone-query-builder/setup.mdx?collection=docs"
import * as __fd_glob_42 from "../docs/standalone-query-builder/query-building.mdx?collection=docs"
import * as __fd_glob_41 from "../docs/standalone-query-builder/execution.mdx?collection=docs"
import * as __fd_glob_40 from "../docs/query-building/where.mdx?collection=docs"
import * as __fd_glob_39 from "../docs/query-building/time-functions.mdx?collection=docs"
import * as __fd_glob_38 from "../docs/query-building/subqueries-ctes.mdx?collection=docs"
import * as __fd_glob_37 from "../docs/query-building/sql-expressions.mdx?collection=docs"
import * as __fd_glob_36 from "../docs/query-building/select.mdx?collection=docs"
import * as __fd_glob_35 from "../docs/query-building/ordering.mdx?collection=docs"
import * as __fd_glob_34 from "../docs/query-building/joins.mdx?collection=docs"
import * as __fd_glob_33 from "../docs/query-building/join-relationships.mdx?collection=docs"
import * as __fd_glob_32 from "../docs/query-building/helper-methods.mdx?collection=docs"
import * as __fd_glob_31 from "../docs/query-building/basics.mdx?collection=docs"
import * as __fd_glob_30 from "../docs/query-building/aggregation.mdx?collection=docs"
import * as __fd_glob_29 from "../docs/query-building/advanced.mdx?collection=docs"
import * as __fd_glob_28 from "../docs/query-building/advanced-filtering.mdx?collection=docs"
import * as __fd_glob_27 from "../docs/react/using-queries.mdx?collection=docs"
import * as __fd_glob_26 from "../docs/react/getting-started.mdx?collection=docs"
import * as __fd_glob_25 from "../docs/react/advanced-patterns.mdx?collection=docs"
import * as __fd_glob_24 from "../docs/why-hypequery.mdx?collection=docs"
import * as __fd_glob_23 from "../docs/vite.mdx?collection=docs"
import * as __fd_glob_22 from "../docs/serve-runtime.mdx?collection=docs"
import * as __fd_glob_21 from "../docs/schemas.mdx?collection=docs"
import * as __fd_glob_20 from "../docs/roadmap.mdx?collection=docs"
import * as __fd_glob_19 from "../docs/quick-start.mdx?collection=docs"
import * as __fd_glob_18 from "../docs/query-definitions.mdx?collection=docs"
import * as __fd_glob_17 from "../docs/observability.mdx?collection=docs"
import * as __fd_glob_16 from "../docs/nodejs.mdx?collection=docs"
import * as __fd_glob_15 from "../docs/nextjs.mdx?collection=docs"
import * as __fd_glob_14 from "../docs/multi-tenancy.mdx?collection=docs"
import * as __fd_glob_13 from "../docs/manual-installation.mdx?collection=docs"
import * as __fd_glob_12 from "../docs/introduction.mdx?collection=docs"
import * as __fd_glob_11 from "../docs/http-openapi.mdx?collection=docs"
import * as __fd_glob_10 from "../docs/fetch.mdx?collection=docs"
import * as __fd_glob_9 from "../docs/faq.mdx?collection=docs"
import * as __fd_glob_8 from "../docs/embedded-runtime.mdx?collection=docs"
import * as __fd_glob_7 from "../docs/core-concepts.mdx?collection=docs"
import * as __fd_glob_6 from "../docs/changelog.mdx?collection=docs"
import * as __fd_glob_5 from "../docs/caching.mdx?collection=docs"
import * as __fd_glob_4 from "../docs/authentication.mdx?collection=docs"
import { default as __fd_glob_3 } from "../docs/standalone-query-builder/query-building/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../docs/query-building/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../docs/standalone-query-builder/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "docs", {"meta.json": __fd_glob_0, "standalone-query-builder/meta.json": __fd_glob_1, "query-building/meta.json": __fd_glob_2, "standalone-query-builder/query-building/meta.json": __fd_glob_3, }, {"authentication.mdx": __fd_glob_4, "caching.mdx": __fd_glob_5, "changelog.mdx": __fd_glob_6, "core-concepts.mdx": __fd_glob_7, "embedded-runtime.mdx": __fd_glob_8, "faq.mdx": __fd_glob_9, "fetch.mdx": __fd_glob_10, "http-openapi.mdx": __fd_glob_11, "introduction.mdx": __fd_glob_12, "manual-installation.mdx": __fd_glob_13, "multi-tenancy.mdx": __fd_glob_14, "nextjs.mdx": __fd_glob_15, "nodejs.mdx": __fd_glob_16, "observability.mdx": __fd_glob_17, "query-definitions.mdx": __fd_glob_18, "quick-start.mdx": __fd_glob_19, "roadmap.mdx": __fd_glob_20, "schemas.mdx": __fd_glob_21, "serve-runtime.mdx": __fd_glob_22, "vite.mdx": __fd_glob_23, "why-hypequery.mdx": __fd_glob_24, "react/advanced-patterns.mdx": __fd_glob_25, "react/getting-started.mdx": __fd_glob_26, "react/using-queries.mdx": __fd_glob_27, "query-building/advanced-filtering.mdx": __fd_glob_28, "query-building/advanced.mdx": __fd_glob_29, "query-building/aggregation.mdx": __fd_glob_30, "query-building/basics.mdx": __fd_glob_31, "query-building/helper-methods.mdx": __fd_glob_32, "query-building/join-relationships.mdx": __fd_glob_33, "query-building/joins.mdx": __fd_glob_34, "query-building/ordering.mdx": __fd_glob_35, "query-building/select.mdx": __fd_glob_36, "query-building/sql-expressions.mdx": __fd_glob_37, "query-building/subqueries-ctes.mdx": __fd_glob_38, "query-building/time-functions.mdx": __fd_glob_39, "query-building/where.mdx": __fd_glob_40, "standalone-query-builder/execution.mdx": __fd_glob_41, "standalone-query-builder/query-building.mdx": __fd_glob_42, "standalone-query-builder/setup.mdx": __fd_glob_43, "standalone-query-builder/standalone-query-builder.mdx": __fd_glob_44, "standalone-query-builder/when-to-use.mdx": __fd_glob_45, "reference/cli.mdx": __fd_glob_46, "reference/connection.mdx": __fd_glob_47, "reference/packages.mdx": __fd_glob_48, "reference/query-builder.mdx": __fd_glob_49, "reference/react.mdx": __fd_glob_50, "reference/serve.mdx": __fd_glob_51, "reference/types.mdx": __fd_glob_52, "standalone-query-builder/query-building/advanced-filtering.mdx": __fd_glob_53, "standalone-query-builder/query-building/advanced.mdx": __fd_glob_54, "standalone-query-builder/query-building/aggregation.mdx": __fd_glob_55, "standalone-query-builder/query-building/basics.mdx": __fd_glob_56, "standalone-query-builder/query-building/helper-methods.mdx": __fd_glob_57, "standalone-query-builder/query-building/join-relationships.mdx": __fd_glob_58, "standalone-query-builder/query-building/joins.mdx": __fd_glob_59, "standalone-query-builder/query-building/ordering.mdx": __fd_glob_60, "standalone-query-builder/query-building/select.mdx": __fd_glob_61, "standalone-query-builder/query-building/sql-expressions.mdx": __fd_glob_62, "standalone-query-builder/query-building/subqueries-ctes.mdx": __fd_glob_63, "standalone-query-builder/query-building/time-functions.mdx": __fd_glob_64, "standalone-query-builder/query-building/where.mdx": __fd_glob_65, });