// @ts-nocheck
import * as __fd_glob_57 from "../docs/standalone-usage/when-to-use.mdx?collection=docs"
import * as __fd_glob_56 from "../docs/standalone-usage/setup.mdx?collection=docs"
import * as __fd_glob_55 from "../docs/standalone-usage/introduction.mdx?collection=docs"
import * as __fd_glob_54 from "../docs/standalone-usage/execution.mdx?collection=docs"
import * as __fd_glob_53 from "../docs/query-building/where.mdx?collection=docs"
import * as __fd_glob_52 from "../docs/query-building/time-functions.mdx?collection=docs"
import * as __fd_glob_51 from "../docs/query-building/subqueries-ctes.mdx?collection=docs"
import * as __fd_glob_50 from "../docs/query-building/sql-expressions.mdx?collection=docs"
import * as __fd_glob_49 from "../docs/query-building/select.mdx?collection=docs"
import * as __fd_glob_48 from "../docs/query-building/ordering.mdx?collection=docs"
import * as __fd_glob_47 from "../docs/query-building/joins.mdx?collection=docs"
import * as __fd_glob_46 from "../docs/query-building/join-relationships.mdx?collection=docs"
import * as __fd_glob_45 from "../docs/query-building/helper-methods.mdx?collection=docs"
import * as __fd_glob_44 from "../docs/query-building/basics.mdx?collection=docs"
import * as __fd_glob_43 from "../docs/query-building/aggregation.mdx?collection=docs"
import * as __fd_glob_42 from "../docs/query-building/advanced.mdx?collection=docs"
import * as __fd_glob_41 from "../docs/query-building/advanced-filtering.mdx?collection=docs"
import * as __fd_glob_40 from "../docs/reference/types.mdx?collection=docs"
import * as __fd_glob_39 from "../docs/reference/standalone-query-builder.mdx?collection=docs"
import * as __fd_glob_38 from "../docs/reference/serve.mdx?collection=docs"
import * as __fd_glob_37 from "../docs/reference/react.mdx?collection=docs"
import * as __fd_glob_36 from "../docs/reference/query-builder.mdx?collection=docs"
import * as __fd_glob_35 from "../docs/reference/packages.mdx?collection=docs"
import * as __fd_glob_34 from "../docs/reference/faq.mdx?collection=docs"
import * as __fd_glob_33 from "../docs/reference/connection.mdx?collection=docs"
import * as __fd_glob_32 from "../docs/reference/cli.mdx?collection=docs"
import * as __fd_glob_31 from "../docs/react/using-queries.mdx?collection=docs"
import * as __fd_glob_30 from "../docs/react/overview.mdx?collection=docs"
import * as __fd_glob_29 from "../docs/react/getting-started.mdx?collection=docs"
import * as __fd_glob_28 from "../docs/react/advanced-patterns.mdx?collection=docs"
import * as __fd_glob_27 from "../docs/cli/getting-started.mdx?collection=docs"
import * as __fd_glob_26 from "../docs/why-hypequery.mdx?collection=docs"
import * as __fd_glob_25 from "../docs/vite.mdx?collection=docs"
import * as __fd_glob_24 from "../docs/serve-runtime.mdx?collection=docs"
import * as __fd_glob_23 from "../docs/schemas.mdx?collection=docs"
import * as __fd_glob_22 from "../docs/roadmap.mdx?collection=docs"
import * as __fd_glob_21 from "../docs/quick-start.mdx?collection=docs"
import * as __fd_glob_20 from "../docs/query-definitions.mdx?collection=docs"
import * as __fd_glob_19 from "../docs/query-definition.mdx?collection=docs"
import * as __fd_glob_18 from "../docs/observability.mdx?collection=docs"
import * as __fd_glob_17 from "../docs/nodejs.mdx?collection=docs"
import * as __fd_glob_16 from "../docs/nextjs.mdx?collection=docs"
import * as __fd_glob_15 from "../docs/multi-tenancy.mdx?collection=docs"
import * as __fd_glob_14 from "../docs/manual-installation.mdx?collection=docs"
import * as __fd_glob_13 from "../docs/introduction.mdx?collection=docs"
import * as __fd_glob_12 from "../docs/http-openapi.mdx?collection=docs"
import * as __fd_glob_11 from "../docs/fetch.mdx?collection=docs"
import * as __fd_glob_10 from "../docs/faq.mdx?collection=docs"
import * as __fd_glob_9 from "../docs/embedded-runtime.mdx?collection=docs"
import * as __fd_glob_8 from "../docs/core-concepts.mdx?collection=docs"
import * as __fd_glob_7 from "../docs/changelog.mdx?collection=docs"
import * as __fd_glob_6 from "../docs/caching.mdx?collection=docs"
import * as __fd_glob_5 from "../docs/authentication.mdx?collection=docs"
import { default as __fd_glob_4 } from "../docs/standalone-usage/meta.json?collection=docs"
import { default as __fd_glob_3 } from "../docs/react/meta.json?collection=docs"
import { default as __fd_glob_2 } from "../docs/query-building/meta.json?collection=docs"
import { default as __fd_glob_1 } from "../docs/cli/meta.json?collection=docs"
import { default as __fd_glob_0 } from "../docs/meta.json?collection=docs"
import { server } from 'fumadocs-mdx/runtime/server';
import type * as Config from '../source.config';

const create = server<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>({"doc":{"passthroughs":["extractedReferences"]}});

export const docs = await create.docs("docs", "docs", {"meta.json": __fd_glob_0, "cli/meta.json": __fd_glob_1, "query-building/meta.json": __fd_glob_2, "react/meta.json": __fd_glob_3, "standalone-usage/meta.json": __fd_glob_4, }, {"authentication.mdx": __fd_glob_5, "caching.mdx": __fd_glob_6, "changelog.mdx": __fd_glob_7, "core-concepts.mdx": __fd_glob_8, "embedded-runtime.mdx": __fd_glob_9, "faq.mdx": __fd_glob_10, "fetch.mdx": __fd_glob_11, "http-openapi.mdx": __fd_glob_12, "introduction.mdx": __fd_glob_13, "manual-installation.mdx": __fd_glob_14, "multi-tenancy.mdx": __fd_glob_15, "nextjs.mdx": __fd_glob_16, "nodejs.mdx": __fd_glob_17, "observability.mdx": __fd_glob_18, "query-definition.mdx": __fd_glob_19, "query-definitions.mdx": __fd_glob_20, "quick-start.mdx": __fd_glob_21, "roadmap.mdx": __fd_glob_22, "schemas.mdx": __fd_glob_23, "serve-runtime.mdx": __fd_glob_24, "vite.mdx": __fd_glob_25, "why-hypequery.mdx": __fd_glob_26, "cli/getting-started.mdx": __fd_glob_27, "react/advanced-patterns.mdx": __fd_glob_28, "react/getting-started.mdx": __fd_glob_29, "react/overview.mdx": __fd_glob_30, "react/using-queries.mdx": __fd_glob_31, "reference/cli.mdx": __fd_glob_32, "reference/connection.mdx": __fd_glob_33, "reference/faq.mdx": __fd_glob_34, "reference/packages.mdx": __fd_glob_35, "reference/query-builder.mdx": __fd_glob_36, "reference/react.mdx": __fd_glob_37, "reference/serve.mdx": __fd_glob_38, "reference/standalone-query-builder.mdx": __fd_glob_39, "reference/types.mdx": __fd_glob_40, "query-building/advanced-filtering.mdx": __fd_glob_41, "query-building/advanced.mdx": __fd_glob_42, "query-building/aggregation.mdx": __fd_glob_43, "query-building/basics.mdx": __fd_glob_44, "query-building/helper-methods.mdx": __fd_glob_45, "query-building/join-relationships.mdx": __fd_glob_46, "query-building/joins.mdx": __fd_glob_47, "query-building/ordering.mdx": __fd_glob_48, "query-building/select.mdx": __fd_glob_49, "query-building/sql-expressions.mdx": __fd_glob_50, "query-building/subqueries-ctes.mdx": __fd_glob_51, "query-building/time-functions.mdx": __fd_glob_52, "query-building/where.mdx": __fd_glob_53, "standalone-usage/execution.mdx": __fd_glob_54, "standalone-usage/introduction.mdx": __fd_glob_55, "standalone-usage/setup.mdx": __fd_glob_56, "standalone-usage/when-to-use.mdx": __fd_glob_57, });