name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allow manual triggering
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      # Set up ClickHouse as a service container
      clickhouse:
        image: clickhouse/clickhouse-server:latest
        ports:
          - 8123:8123
          - 9000:9000
        env:
          CLICKHOUSE_USER: default
          CLICKHOUSE_PASSWORD: hypequery_test
          CLICKHOUSE_DB: test_db
          CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
        options: >-
          --health-cmd "wget --no-verbose --tries=1 --spider http://localhost:8123/ping || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build packages
      run: npm run build
    
    - name: Make scripts executable
      run: chmod +x packages/clickhouse/scripts/run-integration-tests.js
    
    - name: Run integration tests
      run: npm run test:integration
      env:
        # Enable integration tests in CI
        ENABLE_CI_INTEGRATION_TESTS: true
        # Configure ClickHouse connection
        CLICKHOUSE_TEST_HOST: http://localhost:8123
        CLICKHOUSE_TEST_USER: default
        CLICKHOUSE_TEST_PASSWORD: hypequery_test
        CLICKHOUSE_TEST_DB: test_db
        # For debugging
        DEBUG: true 