name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (beta or stable)'
        required: true
        default: 'beta'
        type: choice
        options:
          - beta
          - stable

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Configure Git
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build
        run: npm run build
      
      - name: Remove conflicting tag if exists
        run: |
          # First fetch all tags
          git fetch --tags
          
          # Check if v1.0.0 tag exists and remove it if needed
          if git tag -l | grep -q "v1.0.0"; then
            echo "Removing existing v1.0.0 tag locally"
            git tag -d v1.0.0
            
            echo "Removing existing v1.0.0 tag from remote"
            git push --delete origin v1.0.0 || echo "Tag may not exist on remote or couldn't be deleted"
          fi

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          RELEASE_TYPE: ${{ github.event_name == 'push' && 'beta' || github.event.inputs.release_type }}
        run: |
          cd packages/core
          echo "Publishing $RELEASE_TYPE release..."
          
          if [[ "$RELEASE_TYPE" == "beta" ]]; then
            # For beta releases
            echo "Running semantic-release with beta prerelease tag"
            npx semantic-release --extends ./.releaserc.cjs --no-ci --prerelease beta
          else
            # For stable releases
            echo "Running semantic-release for stable release"
            npx semantic-release --extends ./.releaserc.cjs --no-ci
          fi